delivery/ext/db/models.py
# -*- encoding: utf-8 -*-

from delivery.ext.db import db


class Category(db.Model):
    __tablename__ = "category"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode, unique=True)
    on_menu = db.Column("on_menu", db.Boolean)


class Store(db.Model):
    __tablename__ = "store"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))
    category_id = db.Column(
        "category_id", db.Integer, db.ForeignKey("category.id")
    )
    active = db.Column("active", db.Boolean)

    user = db.relationship("User", foreign_keys=user_id)
    category = db.relationship("Category", foreign_keys=category_id)


class Items(db.Model):
    __tablename__ = "items"
    id = db.Column("id", db.Integer, primary_key=True)
    name = db.Column("name", db.Unicode)
    image = db.Column("image", db.Unicode)
    price = db.Column("price", db.Numeric)
    store_id = db.Column("store_id", db.Integer, db.ForeignKey("store.id"))
    available = db.Column("available", db.Boolean)

    store = db.relationship("Store", foreign_keys=store_id)


class Order(db.Model):
    __tablename__ = "order"
    id = db.Column("id", db.Integer, primary_key=True)
    created_at = db.Column("created_at", db.DateTime)
    completed = db.Column("completed", db.Boolean)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))
    store_id = db.Column("store_id", db.Integer, db.ForeignKey("store.id"))
    address_id = db.Column(
        "address_id", db.Integer, db.ForeignKey("address.id")
    )

    user = db.relationship("User", foreign_keys=user_id)
    store = db.relationship("Store", foreign_keys=store_id)
    address = db.relationship("Address", foreign_keys=address_id)


class OrderItems(db.Model):
    __tablename__ = "order_items"
    order_id = db.Column("order_id", db.Integer, db.ForeignKey("order.id"))
    items_id = db.Column("items_id", db.Integer, db.ForeignKey("items.id"))
    quant = db.Column("quant", db.Integer)
    id = db.Column("id", db.Integer, primary_key=True)

    order = db.relationship("Order", foreign_keys=order_id)
    items = db.relationship("Items", foreign_keys=items_id)


class Checkout(db.Model):
    __tablename__ = "checkout"
    id = db.Column("id", db.Integer, primary_key=True)
    payment = db.Column("payment", db.Unicode)
    total = db.Column("total", db.Numeric)
    created_at = db.Column("created_at", db.DateTime)
    completed = db.Column("completed", db.Boolean)
    order_id = db.Column("order_id", db.Integer, db.ForeignKey("order.id"))

    order = db.relationship("Order", foreign_keys=order_id)


class Address(db.Model):
    __tablename__ = "address"
    id = db.Column("id", db.Integer, primary_key=True)
    zip = db.Column("zip", db.Unicode)
    country = db.Column("country", db.Unicode)
    address = db.Column("address", db.Unicode)
    user_id = db.Column("user_id", db.Integer, db.ForeignKey("user.id"))

    user = db.relationship("User", foreign_keys=user_id)

delivery/app.py
from flask import Flask

#from delivery.ext import admin, auth, cli, config, db, hooks, site, toolbar
from ext import admin, auth, cli, config, db, hooks, site, toolbar

def create_app():
    app = Flask(__name__)
    config.init_app(app)
    db.init_app(app)
    auth.init_app(app)
    admin.init_app(app)
    cli.init_app(app)
    toolbar.init_app(app)
    site.init_app(app)
    hooks.init_app(app)
    return app

if __name__ == '__main__':
    app = creat_app()
    app.run(debug=True)

delivery/ext/api/__init__.py
# vamos criar uma API aqui :)

delivery/ext/db/__init__.py
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
migrate = Migrate()


def init_app(app):
    db.init_app(app)
    migrate.init_app(app, db)

delivery/ext/site/__init__.py
from .main import bp


def init_app(app):
    app.register_blueprint(bp)

delivery/ext/site/controllers.py
def get_all_active_stores():
    """Get all stores¨"""

delivery/ext/site/main.py
from flask import Blueprint, current_app, render_template

bp = Blueprint("site", __name__)


@bp.route("/")
def index():
    print("entrei na funcao main")
    current_app.logger.debug("Entrei na funcao main")
    return render_template("index.html")


@bp.route("/sobre")
def about():
    return render_template("about.html")


@bp.route("/restaurantes")
def restaurants():
    return render_template("restaurants.html")

delivery/templates/about.html
{% extends "base.html" %}

{% block top %}
<section class="hero is-primary">
<div class="hero-body">
    <div class="container">
        <h1>CodeFoods</h1>
    </div>
</div>
</section>
{% endblock %}


{% block main %}
<p>

    O melhor site de delivery
    de comida #vegan do mundo! da twitch!
    e do universo!!!!

</p>
{% endblock %}

delivery/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
    {% endblock head %}
    
    {%block  extra_css %} {% endblock extra_css %}
</head>
  <body>
      

    {% block nav %}
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="https://bulma.io">
            <strong>Vitassa Foods</strong>
          </a>
      
          <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="/">
              Home
            </a>
      
            <a class="navbar-item" href="{{ url_for('site.restaurants') }}">
              Restaurantes
            </a>

            <a class="navbar-item" href="{{ url_for('site.about') }}">
              Sobre
            </a>
      
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                More
              </a>
      
              <div class="navbar-dropdown">
                <a class="navbar-item">
                  Pizza
                </a>
                <a class="navbar-item">
                  Pastel
                </a>
                <a class="navbar-item">
                  Hamburguer
                </a>
                <hr class="navbar-divider">
                <a class="navbar-item">
                  Report an issue
                </a>
              </div>
            </div>
          </div>
      
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-primary">
                  <strong>Sign up</strong>
                </a>
                <a class="button is-light">
                  Log in
                </a>
              </div>
            </div>
          </div>
        </div>
      </nav>
    {% endblock nav%}

    {% block top%}{% endblock top %}



  <section class="section">
    <div class="container">
        {% block main %}{% endblock main%}
    </div>
  </section>

  {% block footer %}
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Bulma</strong> by <a href="https://jgthms.com">Jeremy Thomas</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </footer>

    {% endblock footer%}
  </body>
</html>

delivery/templates/index.html
{% extends "base.html" %}
{% import "macros/list_item.html" as list_item %}


{% block top %}
<section class="hero is-primary">
<div class="hero-body">
    <div class="container">
    <h1 class="title">
        {{ site_name }}
    </h1>
    <h2 class="subtitle">
        {{ site_subtitle }}
    </h2>
    </div>
</div>
</section>
{% endblock top %}



{% block main %}
<div class="columns">
    {{ list_item.cards([1, 2, 3, 4]) }}
</div>
{% endblock main %}

delivery/templates/macros/list_item.html
{% macro cards(items) %}
    {% for item in items %}
    <div class="column">
        <div class="card">
            <div class="card-image">
                <figure class="image is-4by3">
                <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                <div class="media-left">
                    <figure class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                    </figure>
                </div>
                <div class="media-content">
                    <p class="title is-4">John Smith</p>
                    <p class="subtitle is-6">@johnsmith</p>
                </div>
                </div>
            
                <div class="content">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                Phasellus nec iaculis mauris. <a>@bulmaio</a>.
                <a href="#">#css</a> <a href="#">#responsive</a>
                <br>
                <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                </div>
            </div>
            </div>
    </div>
    {% endfor %}
{% endmacro%}

delivery/templates/restaurants.html
{% extends "base.html" %}
{% import "macros/list_item.html" as list_item %}

{% block top %}
<section class="hero is-primary">
<div class="hero-body">
    <div class="container">
    <h1 class="title">
        {{ site_name }}
    </h1>
    <h2 class="subtitle">
        {{ site_subtitle }}
    </h2>
    </div>
</div>
</section>
{% endblock top %}



{% block main %}
<div class="columns">
    {{ list_item.cards([1, 2, 3, 4, 5, 6, 7, 8]) }}
</div>
{% endblock main %}